default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: double-quote-string-fixer
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: ["--wrap", "keep", "--number"]
        exclude: ^\.cursor/
        additional_dependencies:
          - mdformat-gfm
          - mdformat-simple-breaks
